language: android

android:
  components:

    - build-tools-19.1.0

    - android-19

    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support

    - addon-google_apis-google-19

    - sys-img-armeabi-v7a-android-19
    - sys-img-x86-android-17

  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'