package com.judopay.judokit.android.model

data class State(val ISOCode: String, val name: String) {
    override fun toString() = this.name
}

val usStates = listOf(
    State(ISOCode = "AK", name = "Alaska"),
    State(ISOCode = "AZ", name = "Arizona"),
    State(ISOCode = "AR", name = "Arkansas"),
    State(ISOCode = "CA", name = "California"),
    State(ISOCode = "CO", name = "Colorado"),
    State(ISOCode = "CT", name = "Connecticut"),
    State(ISOCode = "DE", name = "Delaware"),
    State(ISOCode = "AL", name = "Alabama"),
    State(ISOCode = "DC", name = "District Of Columbia"),
    State(ISOCode = "FL", name = "Florida"),
    State(ISOCode = "GA", name = "Georgia"),
    State(ISOCode = "HI", name = "Hawaii"),
    State(ISOCode = "ID", name = "Idaho"),
    State(ISOCode = "IL", name = "Illinois"),
    State(ISOCode = "IN", name = "Indiana"),
    State(ISOCode = "IA", name = "Iowa"),
    State(ISOCode = "KS", name = "Kansas"),
    State(ISOCode = "KY", name = "Kentucky"),
    State(ISOCode = "LA", name = "Louisiana"),
    State(ISOCode = "ME", name = "Maine"),
    State(ISOCode = "MD", name = "Maryland"),
    State(ISOCode = "MA", name = "Massachusetts"),
    State(ISOCode = "MI", name = "Michigan"),
    State(ISOCode = "MN", name = "Minnesota"),
    State(ISOCode = "MS", name = "Mississippi"),
    State(ISOCode = "MO", name = "Missouri"),
    State(ISOCode = "MT", name = "Montana"),
    State(ISOCode = "NE", name = "Nebraska"),
    State(ISOCode = "NV", name = "Nevada"),
    State(ISOCode = "NH", name = "New Hampshire"),
    State(ISOCode = "NJ", name = "New Jersey"),
    State(ISOCode = "NM", name = "New Mexico"),
    State(ISOCode = "NY", name = "New York"),
    State(ISOCode = "NC", name = "North Carolina"),
    State(ISOCode = "ND", name = "North Dakota"),
    State(ISOCode = "OH", name = "Ohio"),
    State(ISOCode = "OK", name = "Oklahoma"),
    State(ISOCode = "OR", name = "Oregon"),
    State(ISOCode = "PA", name = "Pennsylvania"),
    State(ISOCode = "RI", name = "Rhode Island"),
    State(ISOCode = "SC", name = "South Carolina"),
    State(ISOCode = "SD", name = "South Dakota"),
    State(ISOCode = "TN", name = "Tennessee"),
    State(ISOCode = "TX", name = "Texas"),
    State(ISOCode = "UT", name = "Utah"),
    State(ISOCode = "VT", name = "Vermont"),
    State(ISOCode = "VA", name = "Virginia"),
    State(ISOCode = "WA", name = "Washington"),
    State(ISOCode = "WV", name = "West Virginia"),
    State(ISOCode = "WI", name = "Wisconsin"),
    State(ISOCode = "WY", name = "Wyoming")
)

val canadaProvincesAndTerritories = listOf(
    State(ISOCode = "AB", name = "Alberta"),
    State(ISOCode = "BC", name = "British Columbia"),
    State(ISOCode = "MB", name = "Manitoba"),
    State(ISOCode = "NB", name = "New Brunswick"),
    State(ISOCode = "NL", name = "Newfoundland and Labrador"),
    State(ISOCode = "NS", name = "Nova Scotia"),
    State(ISOCode = "NT", name = "Northwest Territories"),
    State(ISOCode = "NU", name = "Nunavut"),
    State(ISOCode = "ON", name = "Ontario"),
    State(ISOCode = "PE", name = "Prince Edward Island"),
    State(ISOCode = "QC", name = "Quebec"),
    State(ISOCode = "SK", name = "Saskatchewan"),
    State(ISOCode = "YT", name = "Yukon")
)
