name: Android Build and Test Sample Apps

on:
  pull_request:
jobs:
  build_and_test_sample_apps:
    uses: Judopay/github-actions/.github/workflows/android-build-and-test-sample-apps.yml@master
    secrets: inherit
